### PR TITLE
Docs: Comparison to JavaScript/TypeScript

### PR DESCRIPTION
**Pull request by edemaine**
I'm tempted to move the comparison to CoffeeScript in here too... What do you think?

### CODE REVIEW

**Comment by STRd6** [comment]
It looks like the  `git add` ghost struck again 👻

**Comment by edemaine** [comment]
Oops, sorry about that. Someday I'll learn...

**Comment by edemaine** [comment]
Another possibility for the Comparison to CoffeeScript document would be for it to be a separate docs page, but instead of it being linked from the navbar, the only link is from this page.

**Review by STRd6 — APPROVED** [review]
Nice, looks good!

**Pull request merged**
