### PR TITLE
Bulleted arrays with `.` or `•`

### LINKED ISSUE #803: Bulleted arrays
Inspired by [YAML sequences](https://yaml.org/spec/1.2.2/#821-block-sequences) (which use `-`) and [Markdown lists](https://www.markdownguide.org/basic-syntax/#unordered-lists) (which allow `-`, `+`, or `*`), I propose supporting indented implicit lists with some kind of bullet operator:

```js
x :=
  • name: 'hello'
    value: 'world'
  • name: 'goodbye'
    value: 'world'
  • item
↓↓↓
const x = [
  { name: 'hello',
    value: 'world' },
  { name: 'goodbye',
    value: 'world' },
  item
]
```

For Unicode bullets (`•`), this seems like a no-brainer. The question is what ASCII form(s) it should also have.

* `.` looks a lot like a bullet and isn't currently meaningful when followed by a space. I think this is the current winner.
* `~` looks something like a dash and isn't currently meaningful when followed by a space, though we've occasionally discussed it being used for typing (as it was in my typed CoffeeScript branch).
* `-`, `+`, `*` would be great from a compatibility/familiarity perspective. In particular, I dream of a big YAML subset as being a subset of Civet, in the same way that JSON is a subset of JavaScript. We could also plausibly support them in certain contexts, like right after an assignment as in the example above. But in general we should probably give precedence to these acting like regular binary operators. For example:
  ```js
  test
    - item1
    - item2
  ```
  This should probably remain a subtraction, not an implicit function call `test([item1, item2])`. But I think this is mainly an issue when trying to do indented implicit function calls, which is a bit of an edge case (though admittedly a useful one; implicit objects are used this way all the time). When we're at the "beginning" of an expression, I think we could safely use `-`, `+`, `*`.
* `>` is maybe another related option, inspired by the recent JSX ideas, but it has the same limitations as `-`/`+`/`*`.
* `--` is a reasonable option inspired by en-dash (this is how you type it in LaTeX). `++` doesn't make as much sense, and `**` already means exponentiation (and `>>` already means shift-right). The main issue with doubled operators like this is that they look ugly with 2-spaces indentation:
  ```js
  x :=
    -- name: 'hello'
      value: 'world'
  ```

## Context

Civet (and CoffeeScript) currently lack an implicit array mechanism, unlike objects.
They also have an awkward way to write lists of implicit objects — the dedented comma — which this could be a nicer alternative to.
```coffee
[
  name: 'hello'
  value: 'world'
,
  name: 'goodbye'
  value: 'world'
,
  item
]
```

### PR DESCRIPTION
**Pull request by edemaine**
Fixes #803

### CODE REVIEW

**Comment by bbrk24** [comment]
Can you add `as tuple` or `as const` (or any other type cast, really) to a bulleted array without adding parens?

**Comment by edemaine** [comment]
Good question. No, it's not possible without parens. I think at least `|> as tuple` and `|> as const` should be addable, but even those don't work yet.

I think trailing type casts (`as ...`) in the same places that trailing member/call expressions (and maybe pipes from #1168) would make sense as a separate issue.

**Review by STRd6 — APPROVED** [review]
Thanks for implementing this feature. I'm a little bit scared so I think that means we should do it.

**Comment by edemaine** [comment]
I definitely feel like I'm stretching the grammar a bit here. We lack a nice place to put things that work only at the indentation level, not deeper in an expression. For example, I didn't want to allow something like this:

```js
array.map . foo
          . bar
```

(in particular because `array.map . foo` already has a meaning, involving placeholders)

As a result, it seems like I had to add `(Nested)BulletedArray` in a few too many places. Perhaps this could be cleaned up somehow... I'm open to ideas!

Related, I just added support for trailing members/calls and pipelines after top-level bulleted arrays, enabling `|> as const`. I'm not sure I added it to all the right contexts though...

I think this is a reasonable starting point though, and we can extend/fix as we run into further issues.

**Comment by danielbayley** [comment]
@edemaine Surely YAML-like `-` would make more sense here than `.`, which feels a bit too close to…
~~~ js
object
  .method()
  .chaining()
~~~

**Comment by edemaine** [comment]
@danielbayley How would you distinguish from subtraction?

**Comment by danielbayley** [comment]
> @danielbayley How would you distinguish from subtraction?

Iv’e never personally used, or seen any multiline subtraction expressions in the wild. Which is of course, not to say this edge case doesn’t exist…

Maybe the distinction could be that if there is a newline between `-` entries, then it’s an array, else `-`s on the same line is interpreted as subtraction. Then if you did actually want multiline subtraction, you could just wrap that in parentheses? Something like:
~~~ coffee
total := (
  n
  - 1
  - 1
)
~~~

Although, maybe that isn’t even necessary, given that in order to subtract, the first token after the assignment `=` would be a value to subtract from anyway…

@edemaine What do you think?

**Comment by edemaine** [comment]
My worry is examples like this:

```js
func x
  - y
  - z

// parse 1: subtraction (how Civet works now)
func(x
  - y
  - z)

// parse 2: call with array argument (how . works now)
func(x(
  [ y,
    z]))
```

I guess you're saying to prioritize the latter parse, but I don't see how to obtain subtraction behavior without moving the `-` signs onto the previous line (as requierd in CoffeeScript, but something I really don't like about CoffeeScript). Wrapping in parentheses doesn't help.

**Comment by edemaine** [comment]
One possibility that comes to mind: We could add an opt-in YAML compatibility mode via `"civet yaml"` (or some better name) that
* enables `-` and `*` as bullets, but also
* prevents `-` and `*` from being used as binary operators when preceded by a newline.
 
For some, I can imagine this is a worthwhile trade-off.

**Pull request merged**
