### PR TITLE
xor precedence above ||

### PR DESCRIPTION
**Pull request by edemaine**
This should probably wait until after #1026 gets merged, if this code is moving.

* Put `xor` at a precedence "at the bottom of what Civet considers a binary operator", i.e., just below `||`. Not sure whether it should instead be the same level as `||`.
* Fix a core issue in precedence mangling where a low-precedence operator wouldn't actually process the binary operators in the right-hand side. This should make it possible to implement any precedence in this way, in particular custom operator precedence.
* Fix a bug in precedence mangling where `i` would skip over binary operators if `start` moved back a bunch.

### CODE REVIEW

**Comment by STRd6** [comment]
Big merge is done.

**Comment by edemaine** [comment]
I realized that `^` has precedence between `|` and `&` in JavaScript, so I placed `^^` between `||` and `&&` instead of below `||`.

Given that the `^^` precedence was no longer extreme, I bit the bullet and implemented a general binary operator precedence system, which this was already close to. This should really make it easy to customize operator precedence, once we figure out a syntax. For now, I've also moved the default custom operator precedence to between relational and arithmetic. Previously, it was tighter than everything, which is pretty counterintuitive (see #1007).

Also a new `BinaryOp` type which is nice.

**Comment by edemaine** [comment]
@STRd6 Do you want to review the changes? In particular, changing custom operator precedence is breaking, but probably in a good direction.

**Review by STRd6 — APPROVED** [review]
Looks good! This should help us when we add custom operator precedence at some point.

**Pull request merged**
