### PR TITLE
basic babel plugin

### PR DESCRIPTION
**Pull request by STRd6**
Started on a basic babel plugin. It looks like it works but I still need to add automated testing and some more complex test cases.

### CODE REVIEW

**Comment by STRd6** [comment]
Fixes #536 when complete.

**Review by edemaine — COMMENTED** [review]
Another thought: is it possible for the plugin to have options, which could get passed to Civet `compile`?

Also wonder whether inline sourcemaps should enabled by default. (Probably should test.)

**Comment by STRd6** [comment]
This works fine with simple setups and inline maps. It transpiles to JS then hooks into the default babel parse. In theory it could better hook into the TypeScript babel plugins but I have no idea how they work despite reading through the code.

https://github.com/babel/babel/blob/5f74b510ff251af5bf7fbbf25c1c934ffcb6df52/packages/babel-plugin-syntax-typescript/src/index.ts
https://github.com/babel/babel/blob/5f74b510ff251af5bf7fbbf25c1c934ffcb6df52/packages/babel-plugin-transform-typescript/src/index.ts
https://github.com/babel/babel/blob/5f74b510ff251af5bf7fbbf25c1c934ffcb6df52/packages/babel-preset-typescript/src/index.ts
https://github.com/babel/babel/blob/5f74b510ff251af5bf7fbbf25c1c934ffcb6df52/packages/babel-plugin-syntax-jsx/src/index.ts

Still need to add JSX support.

**Comment by edemaine** [comment]
I wonder if you could do this kind of code to enable TypeScript when we don't have `javascript` turned on?

https://github.com/babel/babel/blob/5f74b510ff251af5bf7fbbf25c1c934ffcb6df52/packages/babel-plugin-syntax-typescript/src/index.ts#L60-L61

Alternatively, does TypeScript (and JSX) just work if those plugins are enabled along with this one? Seems fine to require the user to enable the relevant plugins.  And given that you're passing `opts` through as is, I would have expected code like the above to pass the correct options to the parser. (What error are you getting?)

**Comment by STRd6** [comment]
I'm not going to work on this any more right now but it may be useful for some projects using Babel. If anyone tries it and hits specific issues I can try to look into them when I have time. I figure that getting this out is better that it just sitting in limbo forever.

**Pull request merged**
